### ISSUE TITLE
URL for rendered website

### ISSUE THREAD

**Issue by jennybc** [markrobinsonuzh/2016-07-18-zurich#1]
https://markrobinsonuzh.github.io/2016-07-18-zurich/

At the very least, I can find and click on this here. If you're willing, I like to add the link to rendered GitHub Pages as the website in the description of the underlying repo.

Coupled with "Find us on GitHub", this makes it easy to get from source to rendered and back again.

**Comment by markrobinsonuzh** [comment]
Just added you and Lukas as collaborators, so you can add to the site.

**Comment by jennybc** [comment]
Thanks! I accepted. Apparently that still doesn't give me enough privileges to make this particular change. I think only repo owner can do that.

**Comment by markrobinsonuzh** [comment]
OK, added that now.
